package com.example.do2026;

import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.database.Cursor;import android.database.sqlite.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
    DB db; LinearLayout root,content; int primary=Color.rgb(20,83,45); TextView title;
    String[] dealers={"ছালেকুজ্জামান ফিশ ফিড","জিয়া এন্টারপ্রাইজ","রেজাউল","শহীদ","মানিক","মেসার্স মোরশেদ এন্টারপ্রাইজ","কক্স ট্রেডিং"};
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);seed();showDashboard();}
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.DKGRAY);t.setPadding(18,14,18,14);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
    void base(String name){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,247,246));title=tv(name,21);title.setTextColor(Color.WHITE);title.setBackgroundColor(primary);root.addView(title,new LinearLayout.LayoutParams(-1,70));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    void nav(){LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.HORIZONTAL);String[] a={"হোম","ফিড","পোনা","ডিলার","রেট","রিপোর্ট"};for(String s:a){Button b=btn(s);b.setTextSize(10);n.addView(b,new LinearLayout.LayoutParams(0,62,1));b.setOnClickListener(v->{if(s.equals("হোম"))showDashboard();else if(s.equals("ফিড"))showFeed();else if(s.equals("পোনা"))showFry();else if(s.equals("ডিলার"))showDealers();else if(s.equals("রেট"))showPrices();else showReports();});}root.addView(n);}
    EditText e(String hint){EditText x=new EditText(this);x.setHint(hint);x.setSingleLine(true);content.addView(x,new LinearLayout.LayoutParams(-1,56));return x;}
    Spinner spinner(String label,String[] values){content.addView(tv(label,14));Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values);s.setAdapter(a);content.addView(s,new LinearLayout.LayoutParams(-1,55));return s;}
    void showDashboard(){base("DO 2026 • Dealer Sales & Accounts");content.addView(tv("Version 1",18));Cursor c=db.q("select count(*),coalesce(sum(total),0),coalesce(sum(debit),0),coalesce(sum(credit),0) from feed_sales");c.moveToFirst();double sale=c.getDouble(1),debit=c.getDouble(2),credit=c.getDouble(3);content.addView(card("Feed Transactions: "+c.getInt(0)+"\nFeed Sales: "+money(sale)+"\nFeed Debit: "+money(debit)+"\nFeed Credit: "+money(credit)+"\nFeed Balance: "+money(debit-credit)));Cursor f=db.q("select count(*),coalesce(sum(qty),0),coalesce(sum(total),0),coalesce(sum(debit),0),coalesce(sum(credit),0) from fry");f.moveToFirst();content.addView(card("তেলাপিয়া পোনা\nTransactions: "+f.getInt(0)+"\nQuantity: "+fmt(f.getDouble(1))+" pcs\nTotal: "+money(f.getDouble(2))+"\nBalance: "+money(f.getDouble(3)-f.getDouble(4))));content.addView(tv("Offline SQLite • Feed ledger ও Fry ledger আলাদা",14));nav();}
    TextView card(String s){TextView t=tv(s,17);t.setBackgroundColor(Color.WHITE);return t;}
    String[] dealerArray(){return dealers;}
    void showFeed(){base("Feed Sales / DO Entry");EditText date=e("তারিখ (YYYY-MM-DD)");Spinner ds=spinner("ডিলার / Sub-dealer",dealerArray());EditText code=e("Feed Code");EditText product=e("Feed Name");EditText qty=e("Quantity");EditText rate=e("Dealer Rate");TextView total=tv("Total: ৳0.00",18);content.addView(total);EditText debit=e("Debit");EditText credit=e("Credit");EditText note=e("Note");Button save=btn("SAVE FEED ENTRY");content.addView(save);qty.setOnKeyListener((v,k,event)->{calc(qty,rate,total);return false;});rate.setOnKeyListener((v,k,event)->{calc(qty,rate,total);return false;});save.setOnClickListener(v->{double q=num(qty),r=num(rate),t=q*r;db.exec("insert into feed_sales(date,dealer,code,product,qty,rate,total,debit,credit,note) values(?,?,?,?,?,?,?,?,?,?)",date.getText().toString(),ds.getSelectedItem().toString(),code.getText().toString(),product.getText().toString(),q,r,t,num(debit),num(credit),note.getText().toString());Toast.makeText(this,"Feed entry saved",Toast.LENGTH_SHORT).show();showFeed();});nav();}
    void showFry(){base("তেলাপিয়া পোনা হিসাব");EditText date=e("Delivery Date (YYYY-MM-DD)");Spinner ds=spinner("ডিলারের নাম",dealerArray());EditText type=e("ধরণ");EditText qty=e("পোনার পরিমাণ (পিস)");EditText rate=e("Rate / পিস (Default Dealer ৳1.85)");rate.setText("1.85");TextView total=tv("Total: ৳0.00",18);content.addView(total);EditText debit=e("Debit");EditText credit=e("Credit");Button save=btn("SAVE FRY ENTRY");content.addView(save);qty.setOnKeyListener((v,k,event)->{calc(qty,rate,total);return false;});rate.setOnKeyListener((v,k,event)->{calc(qty,rate,total);return false;});save.setOnClickListener(v->{double q=num(qty),r=num(rate),t=q*r;db.exec("insert into fry(date,dealer,type,qty,rate,total,debit,credit) values(?,?,?,?,?,?,?,?)",date.getText().toString(),ds.getSelectedItem().toString(),type.getText().toString(),q,r,t,num(debit),num(credit));Toast.makeText(this,"পোনার হিসাব saved",Toast.LENGTH_SHORT).show();showFry();});content.addView(tv("MRP: ৳2.00 / পিস",15));nav();}
    void showDealers(){base("Dealer-wise Accounts");Button add=btn("+ ADD DEALER");content.addView(add);add.setOnClickListener(v->{final EditText x=new EditText(this);x.setHint("Dealer name");new AlertDialog.Builder(this).setTitle("Add Dealer").setView(x).setPositiveButton("SAVE",(d,w)->{if(x.getText().length()>0)db.exec("insert or ignore into dealers(name) values(?)",x.getText().toString());showDealers();}).setNegativeButton("CANCEL",null).show();});Cursor c=db.q("select name from dealers order by name");while(c.moveToNext()){String n=c.getString(0);Cursor a=db.q("select coalesce(sum(total),0),coalesce(sum(debit),0),coalesce(sum(credit),0) from feed_sales where dealer=?",new String[]{n});a.moveToFirst();Cursor f=db.q("select coalesce(sum(total),0),coalesce(sum(debit),0),coalesce(sum(credit),0) from fry where dealer=?",new String[]{n});f.moveToFirst();double td=a.getDouble(0)+f.getDouble(0),dbt=a.getDouble(1)+f.getDouble(1),cr=a.getDouble(2)+f.getDouble(2);content.addView(card(n+"\nFeed+Fry Total: ৳"+money(td)+"\nDebit: ৳"+money(dbt)+"  Credit: ৳"+money(cr)+"\nBalance: ৳"+money(dbt-cr)));}nav();}
    void showPrices(){base("Price List • Dealer Rate / MRP");content.addView(tv("Source: Fish Feed Rate PDF dated 15.09.2026; rates effective 17.09.2026",14));Cursor c=db.q("select code,product,dealer_rate,mrp from prices order by id");while(c.moveToNext())content.addView(card(c.getString(1)+"  ["+c.getString(0)+"]\nDealer: ৳"+money(c.getDouble(2))+"   MRP: ৳"+money(c.getDouble(3))));content.addView(card("তেলাপিয়া পোনা\nDealer: ৳1.85 / পিস   MRP: ৳2.00 / পিস"));Button update=btn("PRICE UPDATE");content.addView(update);update.setOnClickListener(v->Toast.makeText(this,"Price update screen can be expanded in the next build",Toast.LENGTH_SHORT).show());nav();}
    void showReports(){base("Reports & History");content.addView(tv("Feed + Tilapia Fry dealer-wise summary",18));Cursor c=db.q("select dealer,sum(total),sum(debit),sum(credit) from (select dealer,total,debit,credit from feed_sales union all select dealer,total,debit,credit from fry) group by dealer order by dealer");while(c.moveToNext())content.addView(tv(c.getString(0)+"\nTotal: ৳"+money(c.getDouble(1))+" | Debit: ৳"+money(c.getDouble(2))+" | Credit: ৳"+money(c.getDouble(3))+" | Balance: ৳"+money(c.getDouble(2)-c.getDouble(3)),15));nav();}
    void calc(EditText q,EditText r,TextView t){t.setText("Total: ৳"+money(num(q)*num(r)));}
    double num(EditText e){try{return Double.parseDouble(e.getText().toString().trim());}catch(Exception x){return 0;}}
    String money(double x){return String.format(Locale.US,"%.2f",x);} String fmt(double x){return String.format(Locale.US,"%.0f",x);}
    void seed(){for(String d:dealers)db.exec("insert or ignore into dealers(name) values(?)",d);if(db.count("prices")>0)return;Object[][]p={
      {"100P","Nursery",120,150},{"1001200","Nursery",86,94},{"001(G)","Pabda/Gulsha/Thai Magur/Shol Nursery Gold Floating",139,154},{"001(G)","Pabda/Gulsha/Thai Magur/Shol Nursery Gold Floating",135,150},{"001","Pabda/Gulsha/Thai Magur/Shol Nursery Floating",129,144},{"001","Pabda/Gulsha/Thai Magur/Shol Nursery Floating",128,143},{"002","Pabda/Gulsha/Thai Magur/Shol Nursery Floating",120,132},{"002","Pabda/Gulsha/Thai Magur/Shol Nursery Floating",119,131},{"003","Pabda/Gulsha/Thai Magur/Shol Nursery Floating",112,122.04},{"003","Pabda/Gulsha/Thai Magur/Shol Nursery Floating",111,121},{"004","Pabda/Gulsha/Thai Magur/Shol Starter Floating",97,106},{"004","Pabda/Gulsha/Thai Magur/Shol Starter Floating",96,105},{"005","Pabda/Gulsha/Thai Magur/Shol Starter Floating",94,102},{"101(P)","Tilapia/Pangus Pre Starter Floating",86.7,93.2},{"101","Tilapia Starter Floating",76,81},{"102","Tilapia Grower Floating",72,77},{"103","Tilapia Finisher Floating",71,76},{"201(P)","Pangus Pre Starter Floating",null,93.2},{"201","Pangus Starter Floating",73,78},{"202","Pangus Grower Floating",69,74},{"203","Pangus Finisher Floating",69,74},{"204","Pangus Finisher Floating Economy",64,59},{"300","Koi/Shing/Magur/Gulsha/Pabda Nursery",87,null},{"301(P)","Koi/Shing/Magur/Gulsha/Pabda Pre Starter Floating",88.2,95.2},{"301","Koi/Shing/Magur/Gulsha/Pabda Starter Floating",80,85.2},{"302","Koi/Shing/Magur/Gulsha/Pabda Grower Floating",78,83.2},{"301(P)(G)","Koi/Shing/Magur/Gulsha/Pabda Pre Starter Floating Gold",92,99},{"301(G)","Koi/Shing/Magur/Gulsha/Pabda Starter Floating Gold",91,98},{"302(G)","Koi/Shing/Magur/Gulsha/Pabda Grower Floating Gold",90,null},{"400","Prawn Nursery",120,150},{"401","Prawn Starter Fine Crumble",100,108},{"402","Prawn Starter Fine Crumble",100,108},{"403","Prawn Starter",100,108},{"404","Prawn Grower",86,92},{"405","Prawn Finisher",83,89},{"601","Tilapia/Pangus Starter Sinking",62.5,67},{"602","Tilapia/Pangus Starter Sinking",61.5,66},{"603","Tilapia/Pangus Grower Sinking",58.7,63.2},{"604","Tilapia/Pangus Finisher Sinking",57.7,62.2},{"605","Carp Finisher Sinking",53.5,58},{"703","Prawn Starter",77.3,null},{"701","Prawn Grower Premium",76.4,81.4},{"705","Prawn Grower Special",66.5,71},{"801","Carp Starter Floating",65.2,70.2},{"802","Carp Grower Floating",63.2,68.2},{"803","Carp Finisher Floating",60.2,65.2},{"901","Carp Starter Sinking",59.7,63.6},{"902","Carp Grower Sinking",56.9,67.4},{"903","Carp Finisher Sinking",53.1,57.6}
    };for(Object[]x:p){double dr=x[2]==null?0:((Number)x[2]).doubleValue(),mr=x[3]==null?0:((Number)x[3]).doubleValue();db.exec("insert into prices(code,product,dealer_rate,mrp) values(?,?,?,?)",x[0],x[1],dr,mr);}}
    static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"do2026_v2.db",null,2);}public void onCreate(SQLiteDatabase d){d.execSQL("create table dealers(id integer primary key,name text unique)");d.execSQL("create table feed_sales(id integer primary key,date text,dealer text,code text,product text,qty real,rate real,total real,debit real,credit real,note text)");d.execSQL("create table fry(id integer primary key,date text,dealer text,type text,qty real,rate real,total real,debit real,credit real)");d.execSQL("create table prices(id integer primary key,code text,product text,dealer_rate real,mrp real)");}public void onUpgrade(SQLiteDatabase d,int o,int n){d.execSQL("drop table if exists feed_sales");d.execSQL("drop table if exists fry");d.execSQL("drop table if exists dealers");d.execSQL("drop table if exists prices");onCreate(d);}Cursor q(String s){return getReadableDatabase().rawQuery(s,null);}Cursor q(String s,String[]a){return getReadableDatabase().rawQuery(s,a);}void exec(String s,Object...a){getWritableDatabase().execSQL(s,a);}int count(String table){Cursor c=q("select count(*) from "+table);c.moveToFirst();return c.getInt(0);}}
}
